/*用户表*/
CREATE TABLE USER(
		ID CHAR(32),
		USERNAME VARCHAR(20) NOT NULL,
		PASSWORD VARCHAR(32) NOT NULL,
		SALT VARCHAR(10) NOT NULL	,
		CONSTRAINT PK_USER PRIMARY KEY (ID)
);

/*角色表*/
CREATE TABLE ROLE(
		ID CHAR(32),
		NAME VARCHAR(20) NOT NULL,
		DESCRIPTION VARCHAR(100),
		CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

/*权限表*/
CREATE TABLE PERMISSION(
		ID CHAR(32),
		NAME VARCHAR(20) NOT NULL,
		PERCODE VARCHAR(20),
		CONSTRAINT PK_PERMISSION PRIMARY KEY (ID)
);

/*用户-角色表*/
CREATE TABLE USER_ROLE(
		ID CHAR(32),
		USER_ID CHAR(32) NOT NULL,
		ROLE_ID CHAR(32) NOT NULL,
		CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID)
);

/*角色-权限表*/
CREATE TABLE ROLE_PERMISSION(
		ID CHAR(32),
		ROLE_ID CHAR(32) NOT NULL,
		PERMISSION_ID CHAR(32) NOT NULL,
		CONSTRAINT PK_ROLE_PERMISSION PRIMARY KEY (ID)
);

/**日志表**/
CREATE TABLE SYSTEM_LOG(
	ID CHAR(32),
	DESCRIPTION VARCHAR(30) NOT NULL,
	METHOD VARCHAR(100) NOT NULL,
	LOGTYPE INT NOT NULL,
	REQUEST_IP VARCHAR(25) NOT NULL,
	EXCEPTION_CODE VARCHAR(30),
	EXCEPTION_DETAIL VARCHAR(500),
	PARAMS VARCHAR(50),
	CREATEBY VARCHAR(10),
	CREATE_DATE TIMESTAMP,
	CONSTRAINT PK_SYSTEM_LOG PRIMARY KEY(ID)
);

/**员工表**/
CREATE TABLE EMPLOYEE(
	ID CHAR(32),
	NAME CHAR(10) NOT NULL COMMENT '员工名称',
	SUBSTITUTE CHAR(10) NULL COMMENT '换班人',
	POSITION INT NOT NULL COMMENT '位置',
	DATE CHAR(10) NOT NULL COMMENT '日期',
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID)
);

/*航班组备注表*/
CREATE TABLE flight_note(
		ID CHAR(32) COMMENT '主鍵id',
		UPDATE_TIME DATETIME COMMENT '最后更新日期',
		UPDATE_USER CHAR(32) COMMENT '最后更新人',
		NOTE_CONTENT varchar(500) COMMENT '备注内容',
		SERIALNO	CHAR(32) COMMENT '航班组号id',
		CREATION_DATE  varchar(30),
		CONSTRAINT PK_flight_note PRIMARY KEY (ID)
);

/*保障动态*/
CREATE TABLE `flight_segment` (
  `ID` char(32) NOT NULL DEFAULT '' COMMENT '主鍵id',
  `FLIGHT_TYPE` char(32) DEFAULT NULL COMMENT '飞机类型',
  `FLIGHT_TYPE_ALIASE` char(32) DEFAULT NULL COMMENT '飞机类型别名',
  `SEAT_TYPE` char(32) DEFAULT NULL COMMENT '座位分类',
  `TASK_TIME_LENGTH` int(11) DEFAULT NULL COMMENT '任务时间长度',
  `WARNING_TIME_LENGTH` int(11) DEFAULT NULL COMMENT '警告时间长度',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

